In [110]:
import pymatgen as pmg
from pymatgen.io.cif import CifParser
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import lammps
import math
import numpy as np

In [111]:
filename = '/home/costrouc/p/dftfit/test_files/structure/LiTaO3-hexagonal.cif'
# filename = '/home/costrouc/p/dftfit/test_files/structure/MgO.cif'
structure = CifParser(filename).get_structures()[0]

In [114]:
lattice = pmg.Lattice.from_parameters(*structure.lattice.abc, *structure.lattice.angles)
s = pmg.Structure(lattice, structure.species, structure.frac_coords, coords_are_cartesian=False)
s.lattice

Lattice
    abc : 5.154280000000002 5.15428 5.474026338640813
 angles : 61.91413609942782 61.91413609942782 59.999999999999986
 volume : 105.70728106112583
      A : 4.54732769701239 0.0 2.426605269586302
      B : 1.6262052171156416 4.246604028614143 2.4266052695863016
      C : 0.0 0.0 5.474026338640813

In [97]:
spga = SpacegroupAnalyzer(structure)
structure = spga.get_conventional_standard_structure()

In [98]:
structure.lattice

Lattice
    abc : 5.154279999999999 5.154279999999999 13.7835
 angles : 90.0 90.0 119.99999999999999
 volume : 317.1218431833773
      A : 2.57714 -4.463737418218056 0.0
      B : 2.57714 4.463737418218056 0.0
      C : 0.0 0.0 13.7835

In [101]:
structure.cart_coords

array([[ 0.        ,  0.        ,  3.8455965 ],
       [ 0.        ,  0.        ,  3.0461535 ],
       [ 2.57714   , -1.48791247,  0.7489035 ],
       [ 2.57714   , -1.48791247,  1.5483465 ],
       [ 2.57714   , -1.48791247,  8.4400965 ],
       [ 2.57714   , -1.48791247,  7.6406535 ],
       [ 2.57714   ,  1.48791247,  5.3434035 ],
       [ 2.57714   ,  1.48791247,  6.1428465 ],
       [ 2.57714   ,  1.48791247, 13.0345965 ],
       [ 2.57714   ,  1.48791247, 12.2351535 ],
       [ 2.57714   ,  4.46373742,  9.9379035 ],
       [ 2.57714   ,  4.46373742, 10.7373465 ],
       [ 0.        ,  0.        ,  0.        ],
       [ 2.57714   ,  1.48791247,  2.29725   ],
       [ 2.57714   , -1.48791247,  4.5945    ],
       [ 0.        ,  0.        ,  6.89175   ],
       [ 2.57714   ,  1.48791247,  9.189     ],
       [ 2.57714   , -1.48791247, 11.48625   ],
       [ 1.01462002,  1.31010693,  0.94692645],
       [ 3.51238411,  0.22363324,  0.94692645],
       [ 3.20441588,  2.92999724,  0.946

In [102]:
lattice = pmg.Lattice.from_parameters(*structure.lattice.abc, *structure.lattice.angles)
s = pmg.Structure(lattice, structure.species, structure.frac_coords, coords_are_cartesian=False)

In [103]:
s.lattice

Lattice
    abc : 5.154279999999999 5.154279999999999 13.7835
 angles : 90.0 90.0 119.99999999999999
 volume : 317.1218431833773
      A : 5.154279999999999 0.0 3.156086251954609e-16
      B : -2.577139999999998 4.463737418218057 3.156086251954609e-16
      C : 0.0 0.0 13.7835

In [104]:
s.cart_coords

array([[ 0.00000000e+00,  0.00000000e+00,  3.84559650e+00],
       [ 0.00000000e+00,  0.00000000e+00,  3.04615350e+00],
       [ 2.57714000e+00,  1.48791247e+00,  7.48903500e-01],
       [ 2.57714000e+00,  1.48791247e+00,  1.54834650e+00],
       [ 2.57714000e+00,  1.48791247e+00,  8.44009650e+00],
       [ 2.57714000e+00,  1.48791247e+00,  7.64065350e+00],
       [ 8.88178420e-16,  2.97582495e+00,  5.34340350e+00],
       [ 8.88178420e-16,  2.97582495e+00,  6.14284650e+00],
       [ 8.88178420e-16,  2.97582495e+00,  1.30345965e+01],
       [ 8.88178420e-16,  2.97582495e+00,  1.22351535e+01],
       [-2.57714000e+00,  4.46373742e+00,  9.93790350e+00],
       [-2.57714000e+00,  4.46373742e+00,  1.07373465e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 8.88178420e-16,  2.97582495e+00,  2.29725000e+00],
       [ 2.57714000e+00,  1.48791247e+00,  4.59450000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  6.89175000e+00],
       [ 8.88178420e-16,  2.97582495e+00

In [105]:
lmp = lammps.Lammps()

In [106]:
elements = lmp.system.add_pymatgen_structure(s)

In [107]:
lmp.box.lengths

(5.154279999999999, 5.154279999999999, 13.7835)

In [108]:
lmp.system.positions

array([[ 1.00000002e-08,  1.00000004e-08,  3.84559651e+00],
       [ 1.00000002e-08,  1.00000003e-08,  3.04615351e+00],
       [ 2.57714001e+00,  1.48791248e+00,  7.48903510e-01],
       [ 2.57714001e+00,  1.48791248e+00,  1.54834651e+00],
       [ 2.57714001e+00,  1.48791248e+00,  8.44009651e+00],
       [ 2.57714001e+00,  1.48791248e+00,  7.64065351e+00],
       [ 1.00000014e-08,  2.97582496e+00,  5.34340351e+00],
       [ 1.00000012e-08,  2.97582496e+00,  6.14284651e+00],
       [ 1.00000016e-08,  2.97582496e+00,  1.30345965e+01],
       [ 1.00000018e-08,  2.97582496e+00,  1.22351535e+01],
       [ 1.00000010e-08,  9.99999975e-09,  9.93790351e+00],
       [ 1.00000009e-08,  9.99999983e-09,  1.07373465e+01],
       [ 1.00000000e-08,  1.00000000e-08,  1.00000000e-08],
       [ 1.00000010e-08,  2.97582496e+00,  2.29725001e+00],
       [ 2.57714001e+00,  1.48791248e+00,  4.59450001e+00],
       [ 1.00000004e-08,  1.00000007e-08,  6.89175001e+00],
       [ 1.00000016e-08,  2.97582496e+00

In [109]:
s.cart_coords - lmp.system.positions

array([[-1.00000002e-08, -1.00000004e-08, -1.00000004e-08],
       [-1.00000002e-08, -1.00000003e-08, -9.99999994e-09],
       [-1.00000004e-08, -1.00000002e-08, -9.99999972e-09],
       [-1.00000004e-08, -9.99999994e-09, -9.99999972e-09],
       [-1.00000004e-08, -1.00000006e-08, -1.00000008e-08],
       [-1.00000004e-08, -1.00000010e-08, -9.99999994e-09],
       [-1.00000005e-08, -1.00000004e-08, -9.99999994e-09],
       [-1.00000003e-08, -1.00000004e-08, -9.99999994e-09],
       [-1.00000007e-08, -1.00000013e-08, -1.00000008e-08],
       [-1.00000009e-08, -1.00000013e-08, -1.00000008e-08],
       [-2.57714001e+00,  4.46373741e+00, -1.00000008e-08],
       [-2.57714001e+00,  4.46373741e+00, -1.00000008e-08],
       [-1.00000000e-08, -1.00000000e-08, -1.00000000e-08],
       [-1.00000001e-08, -1.00000008e-08, -9.99999950e-09],
       [-1.00000008e-08, -1.00000004e-08, -9.99999994e-09],
       [-1.00000004e-08, -1.00000007e-08, -9.99999994e-09],
       [-1.00000007e-08, -1.00000008e-08

In [63]:
bounds, tilts, rotation_matrix = lammps.core.lattice_const_to_lammps_box(structure.lattice.abc, np.array(structure.lattice.angles) * (math.pi/180.0), (0, 0, 0))

In [70]:
m = structure.lattice.matrix

In [74]:
a = lammps.core.lengths_angles_to_matrix(*structure.lattice.abc, *(np.array(structure.lattice.angles) * (math.pi/180.0)))
a

array([[ 5.15428000e+00,  0.00000000e+00,  3.15608625e-16],
       [-2.57714000e+00,  4.46373742e+00,  3.15608625e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.37835000e+01]])

In [75]:
b = np.linalg.solve(a, m)

In [65]:
print(bounds, tilts)
rotation_matrix

[[0, 5.154279999999999], [0, 4.463737418218057], [0, 13.7835]] [-2.577139999999998, 8.439959578023771e-16, 1.4618438802964746e-15]


array([[ 1.00000000e+00,  0.00000000e+00,  6.12323400e-17],
       [ 0.00000000e+00,  1.00000000e+00,  1.06057524e-16],
       [-6.12323400e-17, -1.06057524e-16,  1.00000000e+00]])

In [60]:
np.linalg.inv(rotation_matrix)

array([[ 1.00000000e+00, -6.49415036e-33, -6.12323400e-17],
       [-6.49415036e-33,  1.00000000e+00, -1.06057524e-16],
       [ 6.12323400e-17,  1.06057524e-16,  1.00000000e+00]])

In [81]:
np.linalg.norm(np.dot(lmp.system.positions, b) - structure.cart_coords, axis=1)

array([1.73205087e-08, 1.73205083e-08, 2.97582494e+00, 2.97582494e+00,
       2.97582494e+00, 2.97582494e+00, 2.97582495e+00, 2.97582495e+00,
       2.97582495e+00, 2.97582495e+00, 5.15428000e+00, 5.15428000e+00,
       1.73205081e-08, 2.97582495e+00, 2.97582494e+00, 1.73205087e-08,
       2.97582495e+00, 2.97582494e+00, 1.65705582e+00, 3.51949626e+00,
       4.34202315e+00, 3.59615834e+00, 4.40439166e+00, 1.57260406e+00,
       4.46221932e+00, 3.20474357e+00, 1.95040259e+00, 1.95040258e+00,
       3.20474356e+00, 4.46221932e+00, 1.57260405e+00, 4.40439165e+00,
       3.59615833e+00, 4.34202314e+00, 3.51949625e+00, 1.65705581e+00,
       1.57260405e+00, 4.40439165e+00, 3.59615835e+00, 4.34202314e+00,
       3.51949627e+00, 1.65705581e+00, 4.46221932e+00, 3.20474355e+00,
       1.95040260e+00, 1.95040260e+00, 3.20474356e+00, 4.46221933e+00,
       1.65705580e+00, 3.51949626e+00, 4.34202313e+00, 3.59615835e+00,
       4.40439165e+00, 1.57260404e+00])

In [82]:
structure.lattice.matrix

array([[ 2.57714   , -4.46373742,  0.        ],
       [ 2.57714   ,  4.46373742,  0.        ],
       [ 0.        ,  0.        , 13.7835    ]])

In [85]:
lammps.core.lengths_angles_to_matrix(*structure.lattice.abc, *(np.array(structure.lattice.angles) * (math.pi/180)))

array([[ 5.15428000e+00,  0.00000000e+00,  3.15608625e-16],
       [-2.57714000e+00,  4.46373742e+00,  3.15608625e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.37835000e+01]])

In [87]:
pmg.Lattice.from_parameters(*structure.lattice.abc, *structure.lattice.angles)

Lattice
    abc : 5.154279999999999 5.154279999999999 13.7835
 angles : 90.0 90.0 119.99999999999999
 volume : 317.1218431833773
      A : 5.154279999999999 0.0 3.156086251954609e-16
      B : -2.577139999999998 4.463737418218057 3.156086251954609e-16
      C : 0.0 0.0 13.7835